package models

import (
	"time"

	"github.com/google/uuid"
)

// BrandConfig stores editable brand identity settings
type BrandConfig struct {
	ID               uuid.UUID  `json:"id"`
	AppName          string     `json:"appName"`
	Tagline          string     `json:"tagline"`
	MissionStatement string     `json:"missionStatement"`

	// Colors
	PrimaryColor   string `json:"primaryColor"`
	PrimaryLight   string `json:"primaryLight"`
	PrimaryDark    string `json:"primaryDark"`
	SecondaryColor string `json:"secondaryColor"`
	SecondaryDark  string `json:"secondaryDark"`
	AccentColor    string `json:"accentColor"`
	AccentDark     string `json:"accentDark"`

	// Typography
	HeadingFont string `json:"headingFont"`
	BodyFont    string `json:"bodyFont"`

	// Voice
	BrandVoice        string `json:"brandVoice"`
	WritingGuidelines string `json:"writingGuidelines"`

	// Contact
	WebsiteURL   string `json:"websiteUrl"`
	SupportEmail string `json:"supportEmail"`
	ContactPhone string `json:"contactPhone"`

	// Social
	FacebookURL  string `json:"facebookUrl"`
	TwitterURL   string `json:"twitterUrl"`
	InstagramURL string `json:"instagramUrl"`
	LinkedInURL  string `json:"linkedinUrl"`

	// Legal
	CopyrightText  string `json:"copyrightText"`
	DisclaimerText string `json:"disclaimerText"`

	UpdatedAt time.Time  `json:"updatedAt"`
	UpdatedBy *uuid.UUID `json:"updatedBy,omitempty"`
}

// AssetType constants
const (
	AssetTypeLogo          = "logo"
	AssetTypeBrochure      = "brochure"
	AssetTypeSocialGraphic = "social_graphic"
	AssetTypeStyleGuide    = "style_guide"
)

// Format constants
const (
	FormatPDF = "pdf"
	FormatPNG = "png"
	FormatSVG = "svg"
	FormatJPG = "jpg"
)

// Platform constants
const (
	PlatformFacebook  = "facebook"
	PlatformTwitter   = "twitter"
	PlatformInstagram = "instagram"
	PlatformLinkedIn  = "linkedin"
)

// MarketingAsset represents a generated marketing file
type MarketingAsset struct {
	ID                 uuid.UUID  `json:"id"`
	Name               string     `json:"name"`
	Description        string     `json:"description"`
	AssetType          string     `json:"assetType"`
	Format             string     `json:"format"`
	WidthPx            int        `json:"widthPx"`
	HeightPx           int        `json:"heightPx"`
	FilePath           string     `json:"filePath"`
	FileSizeBytes      int64      `json:"fileSizeBytes"`
	IsAutoGenerated    bool       `json:"isAutoGenerated"`
	GenerationTemplate string     `json:"generationTemplate"`
	LastGeneratedAt    *time.Time `json:"lastGeneratedAt"`
	IsActive           bool       `json:"isActive"`
	CreatedAt          time.Time  `json:"createdAt"`
	UpdatedAt          time.Time  `json:"updatedAt"`
}

// SocialTemplate defines dimensions and config for social media graphics
type SocialTemplate struct {
	ID               uuid.UUID `json:"id"`
	Name             string    `json:"name"`
	Platform         string    `json:"platform"`
	TemplateType     string    `json:"templateType"`
	WidthPx          int       `json:"widthPx"`
	HeightPx         int       `json:"heightPx"`
	HeadlineMaxChars int       `json:"headlineMaxChars"`
	BodyMaxChars     int       `json:"bodyMaxChars"`
	IsActive         bool      `json:"isActive"`
	CreatedAt        time.Time `json:"createdAt"`
}

// MarketingMaterialsData is the full data package for the materials page
type MarketingMaterialsData struct {
	BrandConfig     *BrandConfig      `json:"brandConfig"`
	Logos           []MarketingAsset  `json:"logos"`
	Brochures       []MarketingAsset  `json:"brochures"`
	SocialGraphics  []MarketingAsset  `json:"socialGraphics"`
	SocialTemplates []SocialTemplate  `json:"socialTemplates"`
	Statistics      *MarketingStats   `json:"statistics"`
	Features        []FeatureHighlight `json:"features"`
	ValueProps      []ValueProp       `json:"valueProps"`
}

// MarketingStats for dynamic content
type MarketingStats struct {
	TotalFamilies        int     `json:"totalFamilies"`
	TotalEntries         int     `json:"totalEntries"`
	AverageEntriesPerDay float64 `json:"avgEntriesPerDay"`
	InsightsGenerated    int     `json:"insightsGenerated"`
}

// FeatureHighlight for brochure content
type FeatureHighlight struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Icon        string `json:"icon"`
}

// ValueProp for marketing materials
type ValueProp struct {
	Headline    string `json:"headline"`
	Description string `json:"description"`
	Statistic   string `json:"statistic,omitempty"`
}

// GetDefaultFeatures returns the default feature highlights for marketing materials
func GetDefaultFeatures() []FeatureHighlight {
	return []FeatureHighlight{
		{
			Title:       "15-Category Health Tracking",
			Description: "Track medication, behavior, sleep, diet, therapy, and 10 more categories all in one place.",
			Icon:        "clipboard-list",
		},
		{
			Title:       "AI Pattern Detection",
			Description: "Our three-tier AI engine discovers meaningful correlations you might miss.",
			Icon:        "sparkles",
		},
		{
			Title:       "Multi-User Coordination",
			Description: "Parents, caregivers, and medical providers all stay on the same page.",
			Icon:        "users",
		},
		{
			Title:       "Clinical Transparency",
			Description: "See the data sources and confidence levels behind every insight.",
			Icon:        "shield-check",
		},
		{
			Title:       "Real-Time Alerts",
			Description: "Get notified about medication reminders, pattern changes, and important events.",
			Icon:        "bell",
		},
		{
			Title:       "Privacy First",
			Description: "HIPAA-conscious design with role-based access control keeps your data secure.",
			Icon:        "lock-closed",
		},
	}
}

// GetDefaultValueProps returns the default value propositions
func GetDefaultValueProps() []ValueProp {
	return []ValueProp{
		{
			Headline:    "Track Daily Life",
			Description: "Finally, one central place for all your child's health and behavior data. No more scattered notes or forgotten details.",
			Statistic:   "15 tracking categories",
		},
		{
			Headline:    "Discover Patterns with AI",
			Description: "Our intelligent correlation engine identifies connections between medications, sleep, diet, and behavior that you might miss.",
			Statistic:   "3-tier insight system",
		},
		{
			Headline:    "Coordinate Your Care Team",
			Description: "Get your whole team - family, therapists, doctors - working together with shared access and real-time updates.",
			Statistic:   "Multi-role support",
		},
		{
			Headline:    "Reduce Overwhelm",
			Description: "Transform daily chaos into actionable insights. Spend less time tracking and more time caring.",
			Statistic:   "80% report reduced anxiety",
		},
	}
}

// GetAutismStatistics returns key statistics for marketing materials
func GetAutismStatistics() map[string]string {
	return map[string]string{
		"prevalence":         "1 in 31",
		"prevalence_desc":    "children are diagnosed with autism",
		"mother_depression":  "72.5%",
		"mother_dep_desc":    "of mothers experience depression",
		"annual_cost":        "$17K+",
		"annual_cost_desc":   "annual out-of-pocket costs per family",
		"lifetime_cost":      "$1.4M",
		"lifetime_cost_desc": "lifetime cost per individual with autism",
		"parent_anxiety":     "80%",
		"parent_anx_desc":    "of autism parents report anxiety",
	}
}
