-- Version log entry for the post-00032 silent-empty-UI hotfix bundle.
-- Shipped to prod 2026-05-09 in image bae536e8 immediately after the
-- admin replication slice, after Bryan caught the tickets badge showing
-- 8 with an empty list rendered.

INSERT INTO version_log (id, environment, entry_type, title, description, version, created_by)
VALUES (
    gen_random_uuid(),
    :env,
    'fix',
    'Post-00032 hotfix bundle — swallowed errors + missing GRANT + kind-aware lookups',
    E'## What it does\n\nThree classes of post-00032 regression caught by deep audit after Bryan saw the tickets badge show 8 but the page render empty.\n\n## Root cause #1: Missing GRANT on `users` VIEW for cross-env scoped role\n\nThe `carecomp_support_dev` role (used by dev to connect to prod-RDS support tables via SUPPORT_DB_DSN) had GRANT SELECT on `support_tickets`, `ticket_messages`, and `ticket_attachments` BEFORE the migration but never received a corresponding grant on the new `users` VIEW after 00032 split the table. The list-tickets query LEFT JOINs `users` for denorm email/name, so it failed with `permission denied for view users`. The count-tickets query has no JOIN, so the badge worked.\n\nFixed at the prod RDS DB:\n  GRANT SELECT ON users TO carecomp_support_dev;\n  GRANT SELECT ON admin_users TO carecomp_support_dev;\n  GRANT SELECT ON app_users TO carecomp_support_dev;\n\n## Root cause #2: Handlers swallowed the error and rendered empty UI\n\nThe REAL bug was that GetTickets returned an error which the handler discarded with `tickets, total, _ :=`, then rendered the template with tickets=nil → "No tickets found" empty state. The user-visible mismatch (count=8, list=0) was misleading rather than a 5xx that would surface the underlying failure.\n\nFixed in code (commit 56c9e6e + 40b42ca):\n- internal/handler/admin/ui_handlers.go::TicketsPage propagates GetTickets errors → 500 + log line.\n- ui_handlers.go::TicketDetailPage propagates GetTicketByID + GetTicketMessages errors.\n- ui_handlers.go::UsersPage propagates SearchUsers errors.\n- internal/handler/api/alert_handler.go::DashboardInsights propagates the second GetByChildID call (was silently dropped).\n\n## Root cause #3: Kind-agnostic email lookups in parent-only flows\n\nPost-00032 the same email may exist in BOTH admin_users and app_users. Calling the legacy GetByEmail (which queries the read-only `users` view) returns whichever row the UNION emits first — non-deterministic when same email exists in both tables. This could let an admin password reset accidentally affect a parent account or vice versa.\n\nFixed in code (commit 56c9e6e):\n- internal/service/password_reset_service.go::RequestReset now uses GetAppByEmail (the /api/auth/request-reset endpoint is parent-only).\n- internal/service/user_service.go::GetByEmail switched to GetAppByEmail at the service level (its only callers are family member add/lookup, both parent-side).\n\n## Verification on dev before ship\n\n- Re-running the failing query with carecomp_support_dev role: 8 rows returned (was: permission denied).\n- Parent login still works.\n- Cross-table isolation re-tested: joe@workmaninsurancegroup.com (admin-only) cannot log in via /api/auth/login (parent endpoint) → 401 as expected.\n\n## Commits\n\n56c9e6e fix(admin/post-00032): swallowed errors masked permission gap; kind-aware lookups for parent-only flows\n40b42ca fix(alert/insights): stop swallowing error on second alert query',
    :version,
    :author
);
